/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obligatoriobd;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Agustín
 */
public class VentanaVerReuniones extends javax.swing.JFrame {

    /**
     * Creates new form VentanaVerReuniones
     */
    
    
    DefaultListModel modeloLista;
    ArrayList<Reunion> reuniones = new ArrayList();    
    
   
    
    public VentanaVerReuniones() {
        initComponents();
        ImageIcon icon = new ImageIcon("src/imagenes/fondoCelesteFinoFlecha.jpg");
        this.lblfondoCeleste.setIcon(icon);
        modeloLista = new DefaultListModel();
        //Consulta SQL
        Reunion.buscarReunionesPorUsuario(reuniones, ObligatorioBD.usuarioLoggeado.getId());
        for(Reunion reunion : reuniones){
            String elementoLista;
            elementoLista = reunion.getIDReunion()+" | " +reunion.getNombre();
            modeloLista.addElement(elementoLista);
        }
        listaReuniones.setModel(modeloLista);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAtras = new javax.swing.JLabel();
        lblfondoCeleste = new javax.swing.JLabel();
        panelBlanco = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaReuniones = new javax.swing.JList<>();
        btnAbandonar = new javax.swing.JButton();
        btnCrearReunion = new javax.swing.JButton();
        btnGestionar = new javax.swing.JButton();
        btnInvitaciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(779, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(lblAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 30));

        lblfondoCeleste.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblfondoCeleste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoCelesteFinoFlecha.jpg"))); // NOI18N
        getContentPane().add(lblfondoCeleste, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

        panelBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panelBlanco.setPreferredSize(new java.awt.Dimension(739, 300));

        jScrollPane1.setViewportView(listaReuniones);

        btnAbandonar.setText("Abandonar reunion");
        btnAbandonar.setActionCommand("abandonar");
        btnAbandonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbandonarActionPerformed(evt);
            }
        });

        btnCrearReunion.setText("Crear reunion");
        btnCrearReunion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearReunionActionPerformed(evt);
            }
        });

        btnGestionar.setText("Gestionar reunion");
        btnGestionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarActionPerformed(evt);
            }
        });

        btnInvitaciones.setText("Ver invitaciones");
        btnInvitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvitacionesActionPerformed(evt);
            }
        });

        jLabel1.setText("ID | Reuniones");

        javax.swing.GroupLayout panelBlancoLayout = new javax.swing.GroupLayout(panelBlanco);
        panelBlanco.setLayout(panelBlancoLayout);
        panelBlancoLayout.setHorizontalGroup(
            panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlancoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBlancoLayout.createSequentialGroup()
                        .addComponent(btnInvitaciones)
                        .addGap(36, 36, 36)
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBlancoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAbandonar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGestionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBlancoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrearReunion)
                        .addGap(71, 71, 71))))
        );
        panelBlancoLayout.setVerticalGroup(
            panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlancoLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInvitaciones))
                .addGap(29, 29, 29))
            .addGroup(panelBlancoLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(btnGestionar)
                .addGap(18, 18, 18)
                .addComponent(btnAbandonar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearReunion)
                .addContainerGap())
        );

        getContentPane().add(panelBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbandonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbandonarActionPerformed
         if(this.listaReuniones.getSelectedIndex() >= 0){
            //Tomo el id de la fila seleccionada 
            
            Reunion reunion = reuniones.get(this.listaReuniones.getSelectedIndex());
            
            UsuarioReunion.abandonarReunion(ObligatorioBD.usuarioLoggeado.getId(), reunion.getIDReunion());
            
            //Elimino visualmente el elemento de la lista
            Reunion reunionAux = reuniones.get(this.listaReuniones.getSelectedIndex());
            modeloLista.remove(this.listaReuniones.getSelectedIndex());
            reuniones.remove(reunion);
            
        }
    }//GEN-LAST:event_btnAbandonarActionPerformed

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseClicked
        VentanaPrincipal vent = new VentanaPrincipal();
        vent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblAtrasMouseClicked

    private void btnCrearReunionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearReunionActionPerformed
        VentanaCrearReunion vent = new VentanaCrearReunion();
        vent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearReunionActionPerformed

    private void btnGestionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarActionPerformed
        if(this.listaReuniones.getSelectedIndex() != -1){
            Reunion reunion = reuniones.get(this.listaReuniones.getSelectedIndex());
            if(ObligatorioBD.usuarioLoggeado.getId() == reunion.getIDUsuarioCreador()
                    || Reunion.verificarGestion(ObligatorioBD.usuarioLoggeado.getId(), reunion.getIDReunion())){
                VentanaReunion vent = new VentanaReunion(reuniones.get(this.listaReuniones.getSelectedIndex()));
                vent.setVisible(true);
                this.dispose();  
            } else{
                this.lblError.setText("No tienes permisos para gestionar esta reunion");
            }
            
        }
        
        
    }//GEN-LAST:event_btnGestionarActionPerformed

    private void btnInvitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvitacionesActionPerformed
        VentanaInvitaciones vent = new VentanaInvitaciones();
        vent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInvitacionesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbandonar;
    private javax.swing.JButton btnCrearReunion;
    private javax.swing.JButton btnGestionar;
    private javax.swing.JButton btnInvitaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblfondoCeleste;
    private javax.swing.JList<String> listaReuniones;
    private javax.swing.JPanel panelBlanco;
    // End of variables declaration//GEN-END:variables
}
